pipeline{

    agent any

    stages {

        stage("Checkout repository"){
            steps{
               git url: "https://github.com/rupesh-hub/JENKINS-MASTER.git", branch: "main"
            }

        }

        stage("Setup java environment"){
            steps{
                echo "Setup java environment"
            }
        }

        stage("Build project") {
            steps{
                echo "Build project"
            }
        }
    }

}