pipeline{

    agent any

    environment {
        IMAGE_NAME = 'rupesh1997/jenkins-demo-project:1.0.0'
        PROJECT_NAME = 'jenkins-demo-project'
    }

    stages {

        stage("Checkout repository"){
            steps{
               git url: "https://github.com/rupesh-hub/JENKINS-MASTER.git", branch: "main"
            }
        }

        stage("Build project") {
            steps{
                sh '''
                    cd JENKINS-DEMO-PROJECT-01
                    ./mvnw clean package -DskipTests
                '''
            }
        }

        stage("Unit Tests") {
            steps {

                sh '''
                    cd JENKINS-DEMO-PROJECT-01
                    ./mvnw clean test
                '''

            }
        }

        stage("Trivy File System Scan") {
            steps {
                sh '''
                    cd JENKINS-DEMO-PROJECT-01
                    trivy fs --format table -o trivy-fs-report.html .
                '''
            }
        }

        stage("Build docker image") {
             steps{
                 echo "Building docker image"
                 sh '''
                     cd JENKINS-DEMO-PROJECT-01
                     docker build -f deployment/docker/Dockerfile -t ${IMAGE_NAME} .
                 '''
             }
        }

        stage("Deploy") {
             steps {
                 echo "Deployment to the server"
                 sh '''
                     docker kill ${PROJECT_NAME} && docker rm ${PROJECT_NAME}
                     docker system prune -f
                     docker run -d -p 9090:9090 --name ${PROJECT_NAME} ${IMAGE_NAME}
                 '''
             }
        }
    }

}